---
title: "Kimberley Elcess' Data Science Project Portfolio"
date: "April 28, 2017"
output: github_document
---


## Introduction

Kimberley Elcess is a data scientist with a background in materials science and
engineering who focuses on solving problems in capital-intensive industries.

Specifically, Kimberley employs statistics, machine learning, and visualization
to solve problems and generate insight in entrepreneurial environments using
Excel, R, and Bayesian inference.

## Portfolio Introduction

This data science project portfolio contains 3 projects that cover the full
spectrum of the data science process.

This portfolio's projects apply statistics, machine learning, and visualization
within a data science context to provide value to decision-makers using Excel,
R, and Bayesian inference.

## Portfolio Projects by Data Science Process Step

### Import

#### Downloading Data from World Bank and US Government Websites

To explore the relationship between economic factors and birth rate, locate and
download economic indicator and birth rate data.

### Store

#### Downloading Data from World Bank and US Government Websites

To explore the relationship between economic factors and birth rate, locate and
download economic indicator and birth rate data.

### Extract

#### Visualizing US Birth Rate from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart US
birth rate over a time period with changing economic conditions.

#### Visualizing Birth Rates and Economic Indicators from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart birth
rate and economic indicators for several regions over a time period with
changing economic conditions.

### Organize

#### Visualizing US Birth Rate from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart US
birth rate over a time period with changing economic conditions.

#### Visualizing Birth Rates and Economic Indicators from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart birth
rate and economic indicators for several regions over a time period with
changing economic conditions.

### Tidy

#### Visualizing US Birth Rate from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart US
birth rate over a time period with changing economic conditions.

#### Visualizing Birth Rates and Economic Indicators from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart birth
rate and economic indicators for several regions over a time period with
changing economic conditions.

### Transform

#### Visualizing US Birth Rate from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart US
birth rate over a time period with changing economic conditions.

### Visualize

#### Visualizing US Birth Rate from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart US
birth rate over a time period with changing economic conditions.

#### Visualizing Birth Rates and Economic Indicators from 1998 to 2015

To explore the relationship between economic factors and birth rate, chart birth
rate and economic indicators for several regions over a time period with
changing economic conditions.

### Model

#### Feature Engineering

#### Metric Selection

#### Algorithm Selection

#### Parameter Optimization

#### Deployment

#### Evaluation

### Code

#### Feature Engineering

#### Metric Selection

#### Algorithm Selection

#### Parameter Optimization

#### Deployment

#### Evaluation

### Understand

### Communicate

### Next Steps

### Document

## Portfolio Project Tags

### Tools

* Excel
* WinZip
* Notepad
* R
* RStudio
* plyr
* dplyr
* data.table
* ggplot2

### Techniques

* Direct editing
* Reading fixed-width format text files
* Reading tab-delimited text files
* Selecting features
* Filtering observations
* Combining datasets
* Creating new features by calculation
* Summarizing datasets
* Plotting data
* Customizing plots
* Saving plots

### Data Types

* Population
* Income
* Economic Indicators

### Data Sources

* US Centers for Disease Control
* US Census Bureau
* World Bank

## Contact Details

Kimberley Elcess

kelcess@gmail.com

